/*
Copyright 2021-2022 Red Hat, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/redhat-appstudio/jvm-build-service/pkg/apis/jvmbuildservice/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeJBSConfigs implements JBSConfigInterface
type FakeJBSConfigs struct {
	Fake *FakeJvmbuildserviceV1alpha1
	ns   string
}

var jbsconfigsResource = v1alpha1.SchemeGroupVersion.WithResource("jbsconfigs")

var jbsconfigsKind = v1alpha1.SchemeGroupVersion.WithKind("JBSConfig")

// Get takes name of the jBSConfig, and returns the corresponding jBSConfig object, and an error if there is any.
func (c *FakeJBSConfigs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.JBSConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(jbsconfigsResource, c.ns, name), &v1alpha1.JBSConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.JBSConfig), err
}

// List takes label and field selectors, and returns the list of JBSConfigs that match those selectors.
func (c *FakeJBSConfigs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.JBSConfigList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(jbsconfigsResource, jbsconfigsKind, c.ns, opts), &v1alpha1.JBSConfigList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.JBSConfigList{ListMeta: obj.(*v1alpha1.JBSConfigList).ListMeta}
	for _, item := range obj.(*v1alpha1.JBSConfigList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested jBSConfigs.
func (c *FakeJBSConfigs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(jbsconfigsResource, c.ns, opts))

}

// Create takes the representation of a jBSConfig and creates it.  Returns the server's representation of the jBSConfig, and an error, if there is any.
func (c *FakeJBSConfigs) Create(ctx context.Context, jBSConfig *v1alpha1.JBSConfig, opts v1.CreateOptions) (result *v1alpha1.JBSConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(jbsconfigsResource, c.ns, jBSConfig), &v1alpha1.JBSConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.JBSConfig), err
}

// Update takes the representation of a jBSConfig and updates it. Returns the server's representation of the jBSConfig, and an error, if there is any.
func (c *FakeJBSConfigs) Update(ctx context.Context, jBSConfig *v1alpha1.JBSConfig, opts v1.UpdateOptions) (result *v1alpha1.JBSConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(jbsconfigsResource, c.ns, jBSConfig), &v1alpha1.JBSConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.JBSConfig), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeJBSConfigs) UpdateStatus(ctx context.Context, jBSConfig *v1alpha1.JBSConfig, opts v1.UpdateOptions) (*v1alpha1.JBSConfig, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(jbsconfigsResource, "status", c.ns, jBSConfig), &v1alpha1.JBSConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.JBSConfig), err
}

// Delete takes name of the jBSConfig and deletes it. Returns an error if one occurs.
func (c *FakeJBSConfigs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(jbsconfigsResource, c.ns, name, opts), &v1alpha1.JBSConfig{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeJBSConfigs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(jbsconfigsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.JBSConfigList{})
	return err
}

// Patch applies the patch and returns the patched jBSConfig.
func (c *FakeJBSConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.JBSConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(jbsconfigsResource, c.ns, name, pt, data, subresources...), &v1alpha1.JBSConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.JBSConfig), err
}
