/*
Copyright 2021-2022 Red Hat, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/redhat-appstudio/jvm-build-service/pkg/apis/jvmbuildservice/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeRebuiltArtifacts implements RebuiltArtifactInterface
type FakeRebuiltArtifacts struct {
	Fake *FakeJvmbuildserviceV1alpha1
	ns   string
}

var rebuiltartifactsResource = schema.GroupVersionResource{Group: "jvmbuildservice.io", Version: "v1alpha1", Resource: "rebuiltartifacts"}

var rebuiltartifactsKind = schema.GroupVersionKind{Group: "jvmbuildservice.io", Version: "v1alpha1", Kind: "RebuiltArtifact"}

// Get takes name of the rebuiltArtifact, and returns the corresponding rebuiltArtifact object, and an error if there is any.
func (c *FakeRebuiltArtifacts) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.RebuiltArtifact, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(rebuiltartifactsResource, c.ns, name), &v1alpha1.RebuiltArtifact{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RebuiltArtifact), err
}

// List takes label and field selectors, and returns the list of RebuiltArtifacts that match those selectors.
func (c *FakeRebuiltArtifacts) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.RebuiltArtifactList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(rebuiltartifactsResource, rebuiltartifactsKind, c.ns, opts), &v1alpha1.RebuiltArtifactList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.RebuiltArtifactList{ListMeta: obj.(*v1alpha1.RebuiltArtifactList).ListMeta}
	for _, item := range obj.(*v1alpha1.RebuiltArtifactList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested rebuiltArtifacts.
func (c *FakeRebuiltArtifacts) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(rebuiltartifactsResource, c.ns, opts))

}

// Create takes the representation of a rebuiltArtifact and creates it.  Returns the server's representation of the rebuiltArtifact, and an error, if there is any.
func (c *FakeRebuiltArtifacts) Create(ctx context.Context, rebuiltArtifact *v1alpha1.RebuiltArtifact, opts v1.CreateOptions) (result *v1alpha1.RebuiltArtifact, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(rebuiltartifactsResource, c.ns, rebuiltArtifact), &v1alpha1.RebuiltArtifact{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RebuiltArtifact), err
}

// Update takes the representation of a rebuiltArtifact and updates it. Returns the server's representation of the rebuiltArtifact, and an error, if there is any.
func (c *FakeRebuiltArtifacts) Update(ctx context.Context, rebuiltArtifact *v1alpha1.RebuiltArtifact, opts v1.UpdateOptions) (result *v1alpha1.RebuiltArtifact, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(rebuiltartifactsResource, c.ns, rebuiltArtifact), &v1alpha1.RebuiltArtifact{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RebuiltArtifact), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeRebuiltArtifacts) UpdateStatus(ctx context.Context, rebuiltArtifact *v1alpha1.RebuiltArtifact, opts v1.UpdateOptions) (*v1alpha1.RebuiltArtifact, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(rebuiltartifactsResource, "status", c.ns, rebuiltArtifact), &v1alpha1.RebuiltArtifact{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RebuiltArtifact), err
}

// Delete takes name of the rebuiltArtifact and deletes it. Returns an error if one occurs.
func (c *FakeRebuiltArtifacts) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(rebuiltartifactsResource, c.ns, name, opts), &v1alpha1.RebuiltArtifact{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeRebuiltArtifacts) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(rebuiltartifactsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.RebuiltArtifactList{})
	return err
}

// Patch applies the patch and returns the patched rebuiltArtifact.
func (c *FakeRebuiltArtifacts) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.RebuiltArtifact, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(rebuiltartifactsResource, c.ns, name, pt, data, subresources...), &v1alpha1.RebuiltArtifact{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RebuiltArtifact), err
}
