/*
Copyright 2021-2022 Red Hat, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/redhat-appstudio/jvm-build-service/pkg/apis/jvmbuildservice/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeArtifactBuilds implements ArtifactBuildInterface
type FakeArtifactBuilds struct {
	Fake *FakeJvmbuildserviceV1alpha1
	ns   string
}

var artifactbuildsResource = v1alpha1.SchemeGroupVersion.WithResource("artifactbuilds")

var artifactbuildsKind = v1alpha1.SchemeGroupVersion.WithKind("ArtifactBuild")

// Get takes name of the artifactBuild, and returns the corresponding artifactBuild object, and an error if there is any.
func (c *FakeArtifactBuilds) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ArtifactBuild, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(artifactbuildsResource, c.ns, name), &v1alpha1.ArtifactBuild{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ArtifactBuild), err
}

// List takes label and field selectors, and returns the list of ArtifactBuilds that match those selectors.
func (c *FakeArtifactBuilds) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ArtifactBuildList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(artifactbuildsResource, artifactbuildsKind, c.ns, opts), &v1alpha1.ArtifactBuildList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ArtifactBuildList{ListMeta: obj.(*v1alpha1.ArtifactBuildList).ListMeta}
	for _, item := range obj.(*v1alpha1.ArtifactBuildList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested artifactBuilds.
func (c *FakeArtifactBuilds) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(artifactbuildsResource, c.ns, opts))

}

// Create takes the representation of a artifactBuild and creates it.  Returns the server's representation of the artifactBuild, and an error, if there is any.
func (c *FakeArtifactBuilds) Create(ctx context.Context, artifactBuild *v1alpha1.ArtifactBuild, opts v1.CreateOptions) (result *v1alpha1.ArtifactBuild, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(artifactbuildsResource, c.ns, artifactBuild), &v1alpha1.ArtifactBuild{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ArtifactBuild), err
}

// Update takes the representation of a artifactBuild and updates it. Returns the server's representation of the artifactBuild, and an error, if there is any.
func (c *FakeArtifactBuilds) Update(ctx context.Context, artifactBuild *v1alpha1.ArtifactBuild, opts v1.UpdateOptions) (result *v1alpha1.ArtifactBuild, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(artifactbuildsResource, c.ns, artifactBuild), &v1alpha1.ArtifactBuild{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ArtifactBuild), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeArtifactBuilds) UpdateStatus(ctx context.Context, artifactBuild *v1alpha1.ArtifactBuild, opts v1.UpdateOptions) (*v1alpha1.ArtifactBuild, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(artifactbuildsResource, "status", c.ns, artifactBuild), &v1alpha1.ArtifactBuild{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ArtifactBuild), err
}

// Delete takes name of the artifactBuild and deletes it. Returns an error if one occurs.
func (c *FakeArtifactBuilds) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(artifactbuildsResource, c.ns, name, opts), &v1alpha1.ArtifactBuild{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeArtifactBuilds) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(artifactbuildsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ArtifactBuildList{})
	return err
}

// Patch applies the patch and returns the patched artifactBuild.
func (c *FakeArtifactBuilds) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ArtifactBuild, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(artifactbuildsResource, c.ns, name, pt, data, subresources...), &v1alpha1.ArtifactBuild{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ArtifactBuild), err
}
