#This file is used to enable renovate to update the digests. It is updated by renovate then substituted into the golang code.

FROM quay.io/redhat-appstudio/build-trusted-artifacts:latest@sha256:d3f777436f174351e6e93b088682923bb44320d5de57f5e961825db88300cfd3
