= Development Documentation

This documentation is targeting developers who want to contribute to the caching service.

== Required Tools

* Maven
* Docker (or Podman)

== Building The Container Image

TIP: To get more information on how images can be built with Quarkus please refer to the link:https://quarkus.io/guides/container-image[upstream documentation].

Run following command to build the container image:

----
mvn clean package -pl cache -Dquarkus.container-image.build=true
----

The image will be built using Podman and available locally under the `quay.io/redhat-appstudio/hacbs-jvm-cache`
name.

To push the container image to the registry, run:

----
mvn clean package -pl cache -Dquarkus.container-image.build=true -Dquarkus.container-image.push=true
----

[WARNING]
.Quay Repository Access
==== 
To be able to push the image to the link:https://quay.io/repository/redhat-appstudio/hacbs-jvm-cache?tab=info[main repository]
you will need to be granted access to it.
====

=== Image Tag

The image will be tagged with the current project's version. To specify additional tags the `-Dquarkus.container-image.additional-tags`
can be used, for example:

----
-Dquarkus.container-image.additional-tags=latest
----

=== Development Images

Development images are used to test changes made locally. To be able to use them in a Kubernetes environment we need to
push them to a registry first. This must be a different one from the official registry.

Luckily this can be achieved by overriding the names, for example with the `mvn` invocation, like this:

----
mvn clean package -pl cache -Dquarkus.container-image.build=true -Dquarkus.container-image.push=true -Dquarkus.container-image.group=goldmann
----

This will build the image under the `quay.io/goldmann/hacbs-jvm-cache` and push it to this repository.

Available arguments related to the image name are:

`quarkus.container-image.registry`:: Registry name. By default: `quay.io`.
`quarkus.container-image.group`:: Group (organization) in the registry. By default: `redhat-appstudio`.
`quarkus.container-image.name`:: Name of the image. By default: `hacbs-jvm-cache`.

== Running Locally in Development Mode

----
mvn quarkus:dev -pl cache
----

This will start the caching service on localhost on the `8080` port.

TIP: You can access the Quarkus development UI at http://localhost:8080/q/dev/.

== Deployment

Please follow the deployment documentation available in the root of the documentation.

=== Using Development Images

We can use Kustomize to point to the development images we discussed above. To do this,
create a `development` directory under `deployment/cache/overlays`:

----
mkdir deployment/cache/overlays/development
----

and create a file `kustomization.yaml` with following content:

.kustomization.yaml
[source,yaml]
----
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - "../../base"
  - "../../cache/overlays/development"
  - "../../operator/overlays/development"

images:
  - name: hacbs-jvm-cache
    newName: quay.io/goldmann/hacbs-jvm-cache
    newTag: latest
----

In this file you can customize the descriptors that will be used to deploy
the caching service in your local development environment.

----
kubectl apply -k deployment/cache/overlays/development
----

== Running Tests

Running tests require a container engine to be present. The link:https://www.testcontainers.org/[Testcontainers] framework assumes that Docker is installed and running. It is possible to use Podman
as well, see below.

----
mvn clean test -pl cache -am
----

[NOTE]
.Podman support
====
To be able to use Podman as the container engine for link:https://www.testcontainers.org/[Testcontainers]
you need to expose a socket, this can be done by running this command:

----
systemctl start podman --user
----

Now set environment variables mentioned bellow. This assumes that that your user ID is `1000`.
You can check this by running the `id -u` command.

----
DOCKER_HOST=unix:///run/user/1000/podman/podman.sock
TESTCONTAINERS_CHECKS_DISABLE=true
TESTCONTAINERS_RYUK_DISABLED=true
----

Last step is to make sure Podman can pull images from Docker HUB by default.
Add to the `~/.config/containers/registries.conf` file following content:

----
unqualified-search-registries = ["registry.access.redhat.com", "docker.io", "quay.io"]
short-name-mode="permissive"
----

If you use Visual Studio Code you can add these environment variables to your IDE as well.
Open settings in JSON format and add following content:

[source,json]
----
  "java.test.config": {
    "env": {
      "DOCKER_HOST": "unix:///run/user/1000/podman/podman.sock",
      "TESTCONTAINERS_CHECKS_DISABLE": "true",
      "TESTCONTAINERS_RYUK_DISABLED": "true"
    }
  }
----

This will set environment variables every time you run tests from the IDE.

====


== Hacks

This section contains hacks that can be useful while developing the component.

=== Running In Development Profile On Local Cluster

You can run the application in development profile in your cluster by adding this snippet into your
development Kustomize file:

.kustomization.yaml
[source,yaml]
----
patches:
  - patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/env"
        value:
          - name: QUARKUS_PROFILE
            value: "dev"
    target:
      kind: Deployment
      name: hacbs-jvm-cache
----
