FROM registry.access.redhat.com/ubi8/openjdk-17@sha256:a166bd2fedb99cb62ebf4695ab46e19c7e451f887940cdf0b8245c81e403aea2 AS builder

WORKDIR /work
COPY ./ .

RUN mvn -V -B package -pl cli -am -DskipTests

FROM registry.access.redhat.com/ubi8/openjdk-17-runtime@sha256:be756aba478d3b39f55670cf728c4b333d71f764cf951e22f8b8ee5a68e1179a
WORKDIR /work/

COPY --from=builder /work/cli/target/quarkus-app/lib/ /deployments/lib/
COPY --from=builder /work/cli/target/quarkus-app/*.jar /deployments/
COPY --from=builder /work/cli/target/quarkus-app/app/ /deployments/app/
COPY --from=builder /work/cli/target/quarkus-app/quarkus/ /deployments/quarkus/

EXPOSE 8080
USER 0

ENV AB_JOLOKIA_OFF=""
ENV JAVA_OPTS="-Djava.util.logging.manager=org.jboss.logmanager.LogManager"
ENV JAVA_APP_JAR="/deployments/quarkus-run.jar"
