FROM registry.access.redhat.com/ubi8/openjdk-17@sha256:902b68b31b5d27d7a4be04822d44a98d72919a505d7448f1ac53eff8e26b9f36 AS builder
USER 0
WORKDIR /work
COPY ./ .

RUN mkdir -p /work/cache/target/classes

RUN mvn -V -B package -pl cache -am -Dmaven.test.skip

FROM registry.access.redhat.com/ubi8/openjdk-17-runtime@sha256:d60a6c9cacbe7d99fce259d25e1fdbd32aeaa81f60769afd7a14f72886bc2330
USER 0
WORKDIR /work/

COPY --from=builder /work/cache/target/quarkus-app/lib/ /deployments/lib/
COPY --from=builder /work/cache/target/quarkus-app/*.jar /deployments/
COPY --from=builder /work/cache/target/quarkus-app/app/ /deployments/app/
COPY --from=builder /work/cache/target/quarkus-app/quarkus/ /deployments/quarkus/

EXPOSE 8080
USER 185

ENV AB_JOLOKIA_OFF=""
ENV JAVA_OPTS="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
ENV JAVA_APP_JAR="/deployments/quarkus-run.jar"
