FROM registry.access.redhat.com/ubi8/openjdk-21@sha256:095175ef8573de8055e67bd5c8a21098448ac73db4e0d6ccd5269dd36b4d263c AS builder
USER 0
WORKDIR /work
COPY ./ .

RUN mkdir -p /work/cache/target/classes

RUN mvn -V -B package -pl cache -am -Dmaven.test.skip

FROM registry.access.redhat.com/ubi8/openjdk-21-runtime@sha256:c1bf8370627eaed6711ea22915b476d4216517c35c8f8268c0d39ed983bceaff
USER 0
WORKDIR /work/

COPY --from=builder /work/cache/target/quarkus-app/lib/ /deployments/lib/
COPY --from=builder /work/cache/target/quarkus-app/*.jar /deployments/
COPY --from=builder /work/cache/target/quarkus-app/app/ /deployments/app/
COPY --from=builder /work/cache/target/quarkus-app/quarkus/ /deployments/quarkus/

EXPOSE 8080
USER 185

ENV AB_JOLOKIA_OFF=""
ENV JAVA_OPTS="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
ENV JAVA_APP_JAR="/deployments/quarkus-run.jar"
