//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2021-2022 Red Hat, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactBuild) DeepCopyInto(out *ArtifactBuild) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactBuild.
func (in *ArtifactBuild) DeepCopy() *ArtifactBuild {
	if in == nil {
		return nil
	}
	out := new(ArtifactBuild)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArtifactBuild) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactBuildList) DeepCopyInto(out *ArtifactBuildList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ArtifactBuild, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactBuildList.
func (in *ArtifactBuildList) DeepCopy() *ArtifactBuildList {
	if in == nil {
		return nil
	}
	out := new(ArtifactBuildList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArtifactBuildList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactBuildSpec) DeepCopyInto(out *ArtifactBuildSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactBuildSpec.
func (in *ArtifactBuildSpec) DeepCopy() *ArtifactBuildSpec {
	if in == nil {
		return nil
	}
	out := new(ArtifactBuildSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactBuildStatus) DeepCopyInto(out *ArtifactBuildStatus) {
	*out = *in
	out.SCMInfo = in.SCMInfo
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactBuildStatus.
func (in *ArtifactBuildStatus) DeepCopy() *ArtifactBuildStatus {
	if in == nil {
		return nil
	}
	out := new(ArtifactBuildStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BuildRecipe) DeepCopyInto(out *BuildRecipe) {
	*out = *in
	if in.CommandLine != nil {
		in, out := &in.CommandLine, &out.CommandLine
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IgnoredArtifacts != nil {
		in, out := &in.IgnoredArtifacts, &out.IgnoredArtifacts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BuildRecipe.
func (in *BuildRecipe) DeepCopy() *BuildRecipe {
	if in == nil {
		return nil
	}
	out := new(BuildRecipe)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DependencyBuild) DeepCopyInto(out *DependencyBuild) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DependencyBuild.
func (in *DependencyBuild) DeepCopy() *DependencyBuild {
	if in == nil {
		return nil
	}
	out := new(DependencyBuild)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DependencyBuild) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DependencyBuildList) DeepCopyInto(out *DependencyBuildList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DependencyBuild, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DependencyBuildList.
func (in *DependencyBuildList) DeepCopy() *DependencyBuildList {
	if in == nil {
		return nil
	}
	out := new(DependencyBuildList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DependencyBuildList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DependencyBuildSpec) DeepCopyInto(out *DependencyBuildSpec) {
	*out = *in
	out.ScmInfo = in.ScmInfo
	if in.BuildRecipes != nil {
		in, out := &in.BuildRecipes, &out.BuildRecipes
		*out = make([]*BuildRecipe, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(BuildRecipe)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DependencyBuildSpec.
func (in *DependencyBuildSpec) DeepCopy() *DependencyBuildSpec {
	if in == nil {
		return nil
	}
	out := new(DependencyBuildSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DependencyBuildStatus) DeepCopyInto(out *DependencyBuildStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Contaminants != nil {
		in, out := &in.Contaminants, &out.Contaminants
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CurrentBuildRecipe != nil {
		in, out := &in.CurrentBuildRecipe, &out.CurrentBuildRecipe
		*out = new(BuildRecipe)
		(*in).DeepCopyInto(*out)
	}
	if in.PotentialBuildRecipes != nil {
		in, out := &in.PotentialBuildRecipes, &out.PotentialBuildRecipes
		*out = make([]*BuildRecipe, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(BuildRecipe)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.FailedBuildRecipes != nil {
		in, out := &in.FailedBuildRecipes, &out.FailedBuildRecipes
		*out = make([]*BuildRecipe, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(BuildRecipe)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DependencyBuildStatus.
func (in *DependencyBuildStatus) DeepCopy() *DependencyBuildStatus {
	if in == nil {
		return nil
	}
	out := new(DependencyBuildStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SCMInfo) DeepCopyInto(out *SCMInfo) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SCMInfo.
func (in *SCMInfo) DeepCopy() *SCMInfo {
	if in == nil {
		return nil
	}
	out := new(SCMInfo)
	in.DeepCopyInto(out)
	return out
}
