{
 "title": "JVM Build Service",
 "description": "JVM Build Service Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "ArtifactBuild State",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(stonesoup_jvmbuildservice_artifactbuilds_total_by_state_count) by (state)\n\n",
     "legendFormat": "{{ state }} "
    }
   ]
  },
  {
   "title": "Completed Builds",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(stonesoup_jvmbuildservice_dependencybuilds_total_by_state_count{state=\"DependencyBuildStateComplete\"})",
     "legendFormat": "Complete"
    },
    {
     "expr": "sum(stonesoup_jvmbuildservice_dependencybuilds_total_by_state_count{state=\"DependencyBuildStateFailed\"})",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(stonesoup_jvmbuildservice_dependencybuilds_total_by_state_count{state=\"DependencyBuildStateContaminated\"})",
     "legendFormat": "Contaminated"
    }
   ]
  },
  {
   "title": "Completed Artifacts",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(stonesoup_jvmbuildservice_artifactbuilds_total_by_state_count{state=\"ArtifactBuildComplete\"})",
     "legendFormat": "Complete"
    },
    {
     "expr": "sum(stonesoup_jvmbuildservice_artifactbuilds_total_by_state_count{state=\"ArtifactBuildFailed\"})",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(stonesoup_jvmbuildservice_artifactbuilds_total_by_state_count{state=\"ArtifactBuildMissing\"})",
     "legendFormat": "Missing"
    }
   ]
  },
  {
   "title": "Active Pipelines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(stonesoup_jvmbuildservice_artifactbuilds_total_by_state_count{state=\"ArtifactBuildDiscovering\"})\n",
     "legendFormat": "Active Discovery Pipelines"
    },
    {
     "expr": "(sum(stonesoup_jvmbuildservice_dependencybuilds_total_by_state_count{state=\"DependencyBuildStateAnalyzeBuild\"})or vector(0)) + (sum(stonesoup_jvmbuildservice_dependencybuilds_total_by_state_count{state=\"DependencyBuildStateBuilding\"}) or vector(0)) + (sum(stonesoup_jvmbuildservice_dependencybuilds_total_by_state_count{state=\"DependencyBuildStateSubmitBuild\"}) or vector(0))\n",
     "legendFormat": "Active Builds"
    },
    {}
   ]
  }
 ]
}