apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: sample-discovery-build-
spec:
  taskRef:
    name: lookup-artifact-location
  params:
    - name: GAV
      value: io.quarkus:quarkus-core:2.8.2.Final
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce # access mode may affect how you can use this volume in parallel tasks
          resources:
            requests:
              storage: 1Gi
