apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: wildfly-build-
spec:
  pipelineRef:
    name: sample-component-build
  params:
    - name: url
      value: https://github.com/wildfly/wildfly.git
    - name: app-path
      value: ./ee-dist/target
    - name: revision
      value: f3c78a3aaca3cf0ba3c25b6983628310d3125aea
  workspaces:
    - name: maven-settings
      emptyDir: {}
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce # access mode may affect how you can use this volume in parallel tasks
          resources:
            requests:
              storage: 5Gi
  taskRunSpecs:
    - pipelineTaskName: maven-run
      serviceAccountName: pipeline
