FROM registry.access.redhat.com/ubi9/go-toolset:1.22.5-1731639025@sha256:45170b6e45114849b5d2c0e55d730ffa4a709ddf5f58b9e810548097b085e78f as builder
USER 0
WORKDIR /work
COPY ./ .

RUN go build -o domainproxyserver cmd/domainproxy/server/main.go
RUN go build -o domainproxyclient cmd/domainproxy/client/main.go

FROM quay.io/konflux-ci/buildah-task:latest@sha256:5cbd487022fb7ac476cbfdea25513b810f7e343ec48f89dc6a4e8c3c39fa37a2
USER 0
WORKDIR /work/

COPY --from=builder /work/domainproxyserver /app/domain-proxy-server
COPY --from=builder /work/domainproxyclient /app/domain-proxy-client
