= Deployment

The `deployment` directory contains Kustomize files that can be used to deploy all the components
onto a Kubernetes cluster.

== Requirements

* Kubernetes cluster (link:https://kubernetes.io/docs/tasks/tools/#minikube[minikube] is fine!)
* link:https://kubernetes.io/docs/tasks/tools/#kubectl[kubectl] CLI tool

== Instructions

After starting minikube you can run following command to deploy everything
using the *staging* versions:

----
kubectl apply -k deployment/overlays/staging
----

[NOTE]
====
Please note the `-k` switch. This will generate the resources with Kustomize instead of
applying these files directly as wit would be done with the `-f` flag.

To only generate the output you can use the `kubectl kustomize` command.
====

What this command will do is:

* Install Tekton Pipelines
* Install `git-clone` and `maven` Tekton Tasks
* Install required JVM Build Service components

[NOTE]
====
After running the command on a fresh cluster you may see errors related to missing CustomResourceDefinitions.
This is expected and the reason is that we are installing these CRD's and using them immediately and the cluster
may not register them on time. Just run the above command again after a few seconds.
====

[WARNING]
====
Currently *only staging version are published*.
====

== Local Development

If you want to test your changes locally with your own quay.io account you can do this
using the `dev-template` overlays.

First set the QUAY_USERNAME env variable to your quay username:

----
export QUAY_USERNAME=<<your username>>
----

Now run a maven build with -Dlocal. This will build the images and deploy them to your Quay account:

----
mvn clean package -Dlocal
----

WARNING: This will create private repositories by default, you will need to set them to public
for the next step to work.

Now run the local development script to deploy to minikube:

----
./deployment/development.sh
----

This will generate a new development overlay with your username substituted into the image
names, and then apply this using kubectrl.

If you want to make changes rebuild the module that you have changed with
the maven command above, and then run the following to restart the deployment:

----
kubectl rollout restart deployment <name>
----

Your local code should now be running in minikube.
