/*
Copyright 2021-2022 Red Hat, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ArtifactBuildListerExpansion allows custom methods to be added to
// ArtifactBuildLister.
type ArtifactBuildListerExpansion interface{}

// ArtifactBuildNamespaceListerExpansion allows custom methods to be added to
// ArtifactBuildNamespaceLister.
type ArtifactBuildNamespaceListerExpansion interface{}

// DependencyBuildListerExpansion allows custom methods to be added to
// DependencyBuildLister.
type DependencyBuildListerExpansion interface{}

// DependencyBuildNamespaceListerExpansion allows custom methods to be added to
// DependencyBuildNamespaceLister.
type DependencyBuildNamespaceListerExpansion interface{}

// RebuiltArtifactListerExpansion allows custom methods to be added to
// RebuiltArtifactLister.
type RebuiltArtifactListerExpansion interface{}

// RebuiltArtifactNamespaceListerExpansion allows custom methods to be added to
// RebuiltArtifactNamespaceLister.
type RebuiltArtifactNamespaceListerExpansion interface{}

// TektonWrapperListerExpansion allows custom methods to be added to
// TektonWrapperLister.
type TektonWrapperListerExpansion interface{}

// TektonWrapperNamespaceListerExpansion allows custom methods to be added to
// TektonWrapperNamespaceLister.
type TektonWrapperNamespaceListerExpansion interface{}
