/*
Copyright 2021-2022 Red Hat, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ArtifactBuildListerExpansion allows custom methods to be added to
// ArtifactBuildLister.
type ArtifactBuildListerExpansion interface{}

// ArtifactBuildNamespaceListerExpansion allows custom methods to be added to
// ArtifactBuildNamespaceLister.
type ArtifactBuildNamespaceListerExpansion interface{}

// DependencyBuildListerExpansion allows custom methods to be added to
// DependencyBuildLister.
type DependencyBuildListerExpansion interface{}

// DependencyBuildNamespaceListerExpansion allows custom methods to be added to
// DependencyBuildNamespaceLister.
type DependencyBuildNamespaceListerExpansion interface{}

// JBSConfigListerExpansion allows custom methods to be added to
// JBSConfigLister.
type JBSConfigListerExpansion interface{}

// JBSConfigNamespaceListerExpansion allows custom methods to be added to
// JBSConfigNamespaceLister.
type JBSConfigNamespaceListerExpansion interface{}

// JvmImageScanListerExpansion allows custom methods to be added to
// JvmImageScanLister.
type JvmImageScanListerExpansion interface{}

// JvmImageScanNamespaceListerExpansion allows custom methods to be added to
// JvmImageScanNamespaceLister.
type JvmImageScanNamespaceListerExpansion interface{}

// RebuiltArtifactListerExpansion allows custom methods to be added to
// RebuiltArtifactLister.
type RebuiltArtifactListerExpansion interface{}

// RebuiltArtifactNamespaceListerExpansion allows custom methods to be added to
// RebuiltArtifactNamespaceLister.
type RebuiltArtifactNamespaceListerExpansion interface{}

// SystemConfigListerExpansion allows custom methods to be added to
// SystemConfigLister.
type SystemConfigListerExpansion interface{}

// SystemConfigNamespaceListerExpansion allows custom methods to be added to
// SystemConfigNamespaceLister.
type SystemConfigNamespaceListerExpansion interface{}
