FROM registry.access.redhat.com/ubi8/openjdk-21@sha256:052e7ee5bcbcb4aafeecf654f72de412f906e708e99e87e7f16022b1823e68a5 AS builder
USER 0
WORKDIR /work
COPY ./ .

RUN mkdir -p /work/cache/target/classes

RUN mvn -V -B package -pl cache -am -Dmaven.test.skip

FROM registry.access.redhat.com/ubi8/openjdk-21-runtime@sha256:300a7835f9628ac265419526966d0c56cfc74d80236006a31a299c62026067c6
USER 0
WORKDIR /work/

COPY --from=builder /work/cache/target/quarkus-app/lib/ /deployments/lib/
COPY --from=builder /work/cache/target/quarkus-app/*.jar /deployments/
COPY --from=builder /work/cache/target/quarkus-app/app/ /deployments/app/
COPY --from=builder /work/cache/target/quarkus-app/quarkus/ /deployments/quarkus/

EXPOSE 8080
USER 185

ENV AB_JOLOKIA_OFF=""
ENV JAVA_OPTS="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
ENV JAVA_APP_JAR="/deployments/quarkus-run.jar"
