FROM registry.access.redhat.com/ubi8/openjdk-17@sha256:a166bd2fedb99cb62ebf4695ab46e19c7e451f887940cdf0b8245c81e403aea2 AS builder
USER 0
WORKDIR /work
COPY ./ .

RUN mkdir -p /work/cache/target/classes

RUN mvn -V -B package -pl cache -am -Dmaven.test.skip

FROM registry.access.redhat.com/ubi8/openjdk-17-runtime@sha256:aa92e16bbe5fe1fafc8621de5a1a7a88fb96f5b3db73e5a3218c48f98a49552f
USER 0
WORKDIR /work/

COPY --from=builder /work/cache/target/quarkus-app/lib/ /deployments/lib/
COPY --from=builder /work/cache/target/quarkus-app/*.jar /deployments/
COPY --from=builder /work/cache/target/quarkus-app/app/ /deployments/app/
COPY --from=builder /work/cache/target/quarkus-app/quarkus/ /deployments/quarkus/

EXPOSE 8080
USER 185

ENV AB_JOLOKIA_OFF=""
ENV JAVA_OPTS="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
ENV JAVA_APP_JAR="/deployments/quarkus-run.jar"
