---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: notification
  annotations:
    tekton.dev/pipelines.minVersion: 0.12.1
    tekton.dev/tags: image-build, konflux
  labels:
    app.kubernetes.io/version: "0.1"
    build.appstudio.redhat.com/build_type: docker
spec:
  description: |-
    Notify PNC on pipeline completion
  params:
    - name: STATUS
      description: Aggregate tasks status
      type: string
    - name: NOTIFICATION_CONTEXT
      description: Notification context
      type: string
    - name: ACCESS_TOKEN
      description: Access token for OAuth.
      type: string
      default: ""
    - name: JVM_BUILD_SERVICE_REQPROCESSOR_IMAGE
      description: Name of the processor image. Useful to override for development.
      type: string
      default: "quay.io/redhat-user-workloads/konflux-jbs-pnc-tenant/jvm-build-service/build-request-processor:latest"
  steps:
    - name: notification
      image: $(params.JVM_BUILD_SERVICE_REQPROCESSOR_IMAGE)
      #image: quay.io/redhat-appstudio/build-trusted-artifacts:latest@sha256:81c4864dae6bb11595f657be887e205262e70086a05ed16ada827fd6391926ac
      script: |
        #!/bin/bash
        set -x
        data=""
        if [ $(params.STATUS) == "Failed" ]; then
          echo "Looks like one or more tasks returned failure!"
          data={\"status\":\"$(params.STATUS)\"}
        else
          echo "Notify PNC on pipeline completion"
          data={\"status\":\"$(params.STATUS)\"}
        fi
        echo "Send notification >>\n$data"
        #        curl -v -X POST -H "Content-Type: application/json" \
        #          -H "Authorization: Bearer $(params.ACCESS_TOKEN)" \
        #          --data $data \
        echo "### context: $(params.NOTIFICATION_CONTEXT)"
