---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: pre-build
  annotations:
    tekton.dev/pipelines.minVersion: 0.12.1
    tekton.dev/tags: image-build, konflux
  labels:
    app.kubernetes.io/version: "0.1"
    build.appstudio.redhat.com/build_type: docker
spec:
  description: |-
    Sets up pre-build running the preprocessor, pushing the source and creating the OCI image.
  params:
    - name: IMAGE_URL
      description: URL of the OCI image to use.
      type: string
    - name: NAME
      description: Name of the pipeline run (i.e. unique dependency build name)
      type: string
    - name: RECIPE_IMAGE
      description: The image from the build recipe to use
    - name: BUILD_TOOL
      description: The build tool to use (ant, gradle, maven, sbt).
    - name: BUILD_TOOL_VERSION
      description: The build tool version to use (e.g. 3.9.5)
    - name: JAVA_VERSION
      description: Java version to use (7, 8, 9, 11, 17, 21, 22, 23)
    - name: BUILD_SCRIPT
      description: The build script to embed with the Containerfile
    - name: JVM_BUILD_SERVICE_REQPROCESSOR_IMAGE
      description: Name of the processor image. Useful to override for development.
      type: string
  results:
    - name: PRE_BUILD_IMAGE_DIGEST
      description: Digest of the image just built
  workspaces:
    - description: The git repo will be cloned onto the volume backing this Workspace.
      name: source
      mountPath: /var/workdir
  steps:
    - name: preprocessor
      image: $(params.JVM_BUILD_SERVICE_REQPROCESSOR_IMAGE)
      securityContext:
        runAsUser: 0
      computeResources:
        limits:
          cpu: 300m
          memory: 512Mi
        requests:
          cpu: 10m
          memory: 512Mi
      args:
        - prepare
        - --build-tool-version=$(params.BUILD_TOOL_VERSION)
        - --java-version=$(params.JAVA_VERSION)
        - --recipe-image=$(params.RECIPE_IMAGE)
        - --request-processor-image=$(params.JVM_BUILD_SERVICE_REQPROCESSOR_IMAGE)
        - --type=$(params.BUILD_TOOL)
        - $(workspaces.source.path)/source
      env:
        - name: BUILD_SCRIPT
          value: $(params.BUILD_SCRIPT)
    - name: create-pre-build-image
      image: quay.io/redhat-appstudio/build-trusted-artifacts:latest@sha256:52f1391e6f1c472fd10bb838f64fae2ed3320c636f536014978a5ddbdfc6b3af
      script: |
        echo "Creating pre-build-image archive"
        create-archive --store $(params.IMAGE_URL) $(results.PRE_BUILD_IMAGE_DIGEST.path)=$(workspaces.source.path)/source
      env:
        - name: IMAGE_URL
          value: $(params.IMAGE_URL)
