---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: maven-deployment
  annotations:
    tekton.dev/pipelines.minVersion: 0.12.1
    tekton.dev/tags: image-build, konflux
  labels:
    app.kubernetes.io/version: "0.1"
    build.appstudio.redhat.com/build_type: docker
spec:
  description: |-
    Takes a OCI archive and deploys the result and uploads log to Bifrost
  params:
    - name: IMAGE_URL
      description: Reference to the OCI archive
      type: string
    - name: IMAGE_DIGEST
      description: Digest to use
      type: string
    - name: MVN_REPO
      description: Maven repository to deploy to
      type: string
    - name: MVN_USERNAME
      description: Maven repository username
      type: string
      default: ""
    - name: MVN_PASSWORD
      description: Name of the secret holding the Maven repository password
      type: string
      # https://github.com/tektoncd/pipeline/issues/8249
      default: ""
    - name: MVN_SERVER_ID
      description: Server identification in Maven settings.
      type: string
      default: "indy-mvn"
    - name: ACCESS_TOKEN
      description: Access token for OAuth.
      type: string
      default: ""
    - name: BUILD_ID
      type: string
      default: ""
    - name: BIFROST_URL
      description: bifrost url to upload log
      type: string
      default: ""
    - name: caTrustConfigMapKey
      description: The name of the key in the ConfigMap that contains the
        CA bundle data.
      type: string
      default: ca-bundle.crt
    - name: caTrustConfigMapName
      description: The name of the ConfigMap to read CA bundle data from.
      type: string
      default: trusted-ca
  volumes:
    - name: workdir
      emptyDir: {}
    - name: trusted-ca
      configMap:
        name: $(params.caTrustConfigMapName)
        items:
          - key: $(params.caTrustConfigMapKey)
            path: ca-bundle.crt
        optional: true
  stepTemplate:
    volumeMounts:
      - mountPath: /var/workdir
        name: workdir
  steps:
    - name: restore-trusted-artifact
      image: quay.io/redhat-appstudio/build-trusted-artifacts:latest@sha256:ff35e09ff5c89e54538b50abae241a765b2b7868f05d62c4835bebf0978f3659
      script: |
        echo "Restoring artifacts to workspace"
        URL=$IMAGE_URL
        DIGEST=$IMAGE_DIGEST
        AARCHIVE=$(oras manifest fetch $ORAS_OPTIONS $URL@$DIGEST | jq --raw-output '.layers[0].digest')
        echo "URL $URL DIGEST $DIGEST AARCHIVE $AARCHIVE"
        use-archive oci:$URL@$AARCHIVE=/var/workdir/
      env:
        - name: IMAGE_DIGEST
          value: $(params.IMAGE_DIGEST)
        - name: IMAGE_URL
          value: $(params.IMAGE_URL)
    - name: upload-artifacts
      image: quay.io/konflux-ci/pnc-konflux-tooling:latest@sha256:8c1c50b01c8dc5e3847f2ace4da8d28d255935b15c14d043bb2e819941697b29
      securityContext:
        runAsUser: 0
      computeResources:
        limits:
          cpu: 300m
          memory: 512Mi
        requests:
          cpu: 10m
          memory: 512Mi
      volumeMounts:
        - mountPath: /mnt/trusted-ca
          name: trusted-ca
          readOnly: true
      env:
        - name: ACCESS_TOKEN
          value: $(params.ACCESS_TOKEN)
      args:
        - deploy
        - --directory=/var/workdir/deployment
        - --mvn-repo=$(params.MVN_REPO)
        - --mvn-username=$(params.MVN_USERNAME)
        - --server-id=$(params.MVN_SERVER_ID)
      script: |
        #!/bin/bash
        set -e
        ca_bundle=/mnt/trusted-ca/ca-bundle.crt
        if [ -f "$ca_bundle" ]; then
          echo "INFO: Using mounted CA bundle: $ca_bundle"
          cp -vf $ca_bundle /etc/pki/ca-trust/source/anchors
          update-ca-trust
        fi
        /opt/jboss/container/java/run/run-java.sh $@
    - name: upload-log
      image: quay.io/konflux-ci/pnc-konflux-tooling:latest@sha256:8c1c50b01c8dc5e3847f2ace4da8d28d255935b15c14d043bb2e819941697b29
      securityContext:
        runAsUser: 0
      computeResources:
        limits:
          cpu: 300m
          memory: 512Mi
        requests:
          cpu: 10m
          memory: 512Mi
      volumeMounts:
        - mountPath: /mnt/trusted-ca
          name: trusted-ca
          readOnly: true
      env:
        - name: ACCESS_TOKEN
          value: $(params.ACCESS_TOKEN)
      args:
        - upload-log
        - --file=/var/workdir/log/build.log
        - --bifrost-url=$(params.BIFROST_URL)
        - --process-context=$(params.BUILD_ID)
        - --process-context-variant=""
        - --tmp=false
        - --request-context=""
      script: |
        #!/bin/bash
        set -e
        ca_bundle=/mnt/trusted-ca/ca-bundle.crt
        if [ -f "$ca_bundle" ]; then
          echo "INFO: Using mounted CA bundle: $ca_bundle"
          cp -vf $ca_bundle /etc/pki/ca-trust/source/anchors
          update-ca-trust
        fi
        /opt/jboss/container/java/run/run-java.sh $@
