FROM quay.io/konflux-ci/buildah-task:latest@sha256:5cbd487022fb7ac476cbfdea25513b810f7e343ec48f89dc6a4e8c3c39fa37a2
USER 0
RUN microdnf install -y iproute
COPY domain-proxy/domain-proxy-server /app/domain-proxy-server
COPY domain-proxy/domain-proxy-client /app/domain-proxy-client

