/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.redhat.hacbs.gradle;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.regex.Pattern;

import org.gradle.testkit.runner.BuildResult;
import org.gradle.testkit.runner.GradleRunner;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

/**
 * Functional test for the 'com.redhat.hacbs.buildinformation' plugin.
 */
class BuildInformationPluginFunctionalTest {
    private static final String GRADLE_VERSION = "7.5";

    private static final String SCRIPT = "plugins {\n    id('com.redhat.hacbs.buildinformation')\n}\n";

    @Test
    void testRunBuildInformationTask(@TempDir Path projectDir) throws IOException {
        Files.write(projectDir.resolve("settings.gradle"), "\n".getBytes(StandardCharsets.UTF_8));
        Files.write(projectDir.resolve("build.gradle"), SCRIPT.getBytes(StandardCharsets.UTF_8));
        GradleRunner runner = GradleRunner.create().withGradleVersion(GRADLE_VERSION).forwardOutput()
                .withPluginClasspath().withArguments("buildinformation").withProjectDir(projectDir.toFile());
        BuildResult result = runner.build();
        assertThat(result.getOutput()).containsPattern(".*javaVersion=17.*")
                .containsPattern(".*plugins=\\[.*" + Pattern.quote("com.redhat.hacbs.gradle.BuildInformationPlugin") + ".*].*");
    }
}
