FROM quay.io/konflux-ci/buildah-task:latest@sha256:5cbd487022fb7ac476cbfdea25513b810f7e343ec48f89dc6a4e8c3c39fa37a2
USER 0
RUN microdnf install -y iproute net-tools java-21-openjdk.x86_64
COPY java-components/domain-proxy/client/target/quarkus-app/lib/ /domain-proxy-client/quarkus-app/lib/
COPY java-components/domain-proxy/client/target/quarkus-app/*.jar /domain-proxy-client/quarkus-app/
COPY java-components/domain-proxy/client/target/quarkus-app/app/ /domain-proxy-client/quarkus-app/app/
COPY java-components/domain-proxy/client/target/quarkus-app/quarkus/ /domain-proxy-client/quarkus-app/quarkus/
COPY java-components/domain-proxy/server/target/quarkus-app/lib/ /domain-proxy-server/quarkus-app/lib/
COPY java-components/domain-proxy/server/target/quarkus-app/*.jar /domain-proxy-server/quarkus-app/
COPY java-components/domain-proxy/server/target/quarkus-app/app/ /domain-proxy-server/quarkus-app/app/
COPY java-components/domain-proxy/server/target/quarkus-app/quarkus/ /domain-proxy-server/quarkus-app/quarkus/
