FROM quay.io/konflux-ci/buildah-task:latest@sha256:218d526bbaf0ceee4d6b4ee78af5e22de786cf2ed7c13f8a915263a43ac50f7a
USER 0
RUN microdnf install -y iproute
COPY domain-proxy/client/target/domain-proxy-client-999-SNAPSHOT-runner /app/domain-proxy-client-runner
COPY domain-proxy/server/target/domain-proxy-server-999-SNAPSHOT-runner /app/domain-proxy-server-runner
