FROM registry.access.redhat.com/quarkus/mandrel-for-jdk-21-rhel8@sha256:cff22db0a64b21935a489c60898957a6f14a39d49281603aba2bba3c1c55554b AS builder
USER 0
WORKDIR /work
COPY ./ .

RUN domain-proxy/mvnw -V -B package -pl domain-proxy/client,domain-proxy/server -am -Dmaven.test.skip

FROM quay.io/konflux-ci/buildah-task:latest@sha256:5cbd487022fb7ac476cbfdea25513b810f7e343ec48f89dc6a4e8c3c39fa37a2
USER 0
RUN microdnf install -y iproute
WORKDIR /work/

COPY --from=builder /work/domain-proxy/client/target/domain-proxy-client-999-SNAPSHOT-runner /app/domain-proxy-client-runner
COPY --from=builder /work/domain-proxy/server/target/domain-proxy-server-999-SNAPSHOT-runner /app/domain-proxy-server-runner
