FROM registry.access.redhat.com/quarkus/mandrel-for-jdk-21-rhel8@sha256:9fc9c79d04817bbabe2708ee5151769deb470dc9612279384daf4b773c1c4c63 AS builder
USER 0
WORKDIR /work
COPY ./ .

RUN domain-proxy/mvnw -V -B package -pl domain-proxy/client,domain-proxy/server -am -Dmaven.test.skip

FROM quay.io/konflux-ci/buildah-task:latest@sha256:218d526bbaf0ceee4d6b4ee78af5e22de786cf2ed7c13f8a915263a43ac50f7a
USER 0
RUN microdnf install -y iproute
WORKDIR /work/

COPY --from=builder /work/domain-proxy/client/target/domain-proxy-client-999-SNAPSHOT-runner /app/domain-proxy-client-runner
COPY --from=builder /work/domain-proxy/server/target/domain-proxy-server-999-SNAPSHOT-runner /app/domain-proxy-server-runner
