apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: jvm-build-request-processor-on-pull-request
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/max-keep-runs: "2"
spec:
  params:
    - name: git-url
      value: "{{repo_url}}"
    - name: revision
      value: "{{revision}}"
    - name: output-image
      value: "quay.io/redhat-appstudio/pull-request-builds:jvmbuildrequestp-{{revision}}"
    - name: path-context
      value: java-components
    - name: dockerfile
      value: build-request-processor/src/main/docker/Dockerfile.all-in-one
  pipelineRef:
    resolver: bundles
    params:
      - name: bundle
        value: quay.io/redhat-appstudio-tekton-catalog/pipeline-core-services-docker-build:latest@sha256:e8428c02b5cff694e543f4c69470a9abd3b97ea014b6bb935de576a2101d84a4
      - name: name
        value: docker-build
      - name: kind
        value: Pipeline
  workspaces:
    - name: workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
