apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: jvm-build-cache-on-pull-request
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/max-keep-runs: "2"
spec:
  params:
    - name: git-url
      value: "{{repo_url}}"
    - name: revision
      value: "{{revision}}"
    - name: output-image
      value: "quay.io/redhat-appstudio/pull-request-builds:jvmcache-{{revision}}"
    - name: path-context
      value: java-components
    - name: dockerfile
      value: cache/src/main/docker/Dockerfile.all-in-one
  pipelineRef:
    name: docker-build
    bundle: quay.io/redhat-appstudio/build-templates-bundle:devel
  workspaces:
    - name: registry-auth
      secret:
        secretName: redhat-appstudio-staginguser-pull-secret
    - name: workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
