apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: jvm-build-controller-on-push
  annotations:
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/max-keep-runs: "15"
spec:
  params:
    - name: git-url
      value: "{{repo_url}}"
    - name: revision
      value: "{{revision}}"
    - name: output-image
      value: 'quay.io/redhat-appstudio/hacbs-jvm-controller:{{revision}}'
    - name: path-context
      value: .
    - name: dockerfile
      value: Dockerfile
    - name: infra-deployment-update-script
      value: |
        sed -i -E 's/[0-9a-f]{40}/{{ revision }}/g' components/jvm-build-service/kustomization.yaml
        sed -i -E 's/[0-9a-f]{40}/{{ revision }}/g' components/jvm-build-service/operator_env_patch.yaml
  pipelineRef:
    name: docker-build
    bundle: quay.io/redhat-appstudio-tekton-catalog/pipeline-core-services-docker-build:latest
  workspaces:
    - name: workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
