apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: jvm-build-controller-on-push
  annotations:
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/max-keep-runs: "15"
spec:
  params:
    - name: git-url
      value: "{{repo_url}}"
    - name: revision
      value: "{{revision}}"
    - name: output-image
      value: 'quay.io/redhat-appstudio/hacbs-jvm-controller:{{revision}}'
    - name: path-context
      value: .
    - name: dockerfile
      value: Dockerfile
    - name: infra-deployment-update-script
      value: |
        sed -i -E 's/[0-9a-f]{40}/{{ revision }}/g' components/jvm-build-service/base/kustomization.yaml
        sed -i -E 's/[0-9a-f]{40}/{{ revision }}/g' components/jvm-build-service/base/operator_env_patch.yaml
        sed -i -E 's/[0-9a-f]{40}/{{ revision }}/g' components/monitoring/grafana/base/dashboards/jvm-build-service/kustomization.yaml
    - name: slack-webhook-notification-team
      value: build
  pipelineRef:
    resolver: bundles
    params:
      - name: bundle
        value: quay.io/redhat-appstudio-tekton-catalog/pipeline-core-services-docker-build:latest@sha256:e8428c02b5cff694e543f4c69470a9abd3b97ea014b6bb935de576a2101d84a4
      - name: name
        value: docker-build
      - name: kind
        value: Pipeline
  workspaces:
    - name: workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
