server-domain-socket=${DOMAIN_SOCKET:/tmp/domain-server.sock}
server-http-port=2000
byte-buffer-size=${BYTE_BUFFER_SIZE:1024}
proxy-target-whitelist=${PROXY_TARGET_WHITELIST:repo.maven.apache.org,repository.jboss.org,packages.confluent.io,jitpack.io,repo.gradle.org,plugins.gradle.org}
quarkus.rest-client.proxy-address=${INTERNAL_PROXY_ADDRESS:indy-generic-proxy:80}
quarkus.rest-client.proxy-user=${INTERNAL_PROXY_USER}
quarkus.rest-client.proxy-password=${INTERNAL_PROXY_PASSWORD}
quarkus.rest-client.non-proxy-hosts=${INTERNAL_NON_PROXY_HOSTS:localhost}
quarkus.log.min-level=ALL
quarkus.log.level=ALL
quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss,SSS} [Domain Proxy Server] %-5p [%c{3.}] (%t) %s%e%n
