FROM registry.access.redhat.com/ubi8/openjdk-17@sha256:632e78989471859ca4ed1148b951a911f7e3b6e6516482be20967c4171612c55 AS builder
USER 0
WORKDIR /work
COPY ./ .

RUN mvn -V -B package -pl build-request-processor -am -Dmaven.test.skip

FROM registry.access.redhat.com/ubi8/openjdk-17-runtime@sha256:e2f33a6c60db4f4e70882a4a557eec5890997f8a1be7e3eb8971a0ff8a45a1a8
USER 0
WORKDIR /work/

COPY --from=builder /work/build-request-processor/target/quarkus-app/lib/ /deployments/lib/
COPY --from=builder /work/build-request-processor/target/quarkus-app/*.jar /deployments/
COPY --from=builder /work/build-request-processor/target/quarkus-app/app/ /deployments/app/
COPY --from=builder /work/build-request-processor/target/quarkus-app/quarkus/ /deployments/quarkus/

EXPOSE 8080
USER 185

ENV AB_JOLOKIA_OFF=""
ENV JAVA_OPTS="-Djava.util.logging.manager=org.jboss.logmanager.LogManager"
ENV JAVA_APP_JAR="/deployments/quarkus-run.jar"
