FROM registry.access.redhat.com/ubi8/openjdk-17@sha256:06497867ab5548aa18379c4389ce062a7aee8061f5a7b18607888dc42c6fe31d AS builder
USER 0
WORKDIR /work
COPY ./ .

RUN mvn -V -B package -pl build-request-processor -am -Dmaven.test.skip

FROM registry.access.redhat.com/ubi8/openjdk-17-runtime@sha256:1f15011cccf53f31591b2675c9967f50cec1434c212888a55916cbfdf3ccaf9d
USER 0
WORKDIR /work/

COPY --from=builder /work/build-request-processor/target/quarkus-app/lib/ /deployments/lib/
COPY --from=builder /work/build-request-processor/target/quarkus-app/*.jar /deployments/
COPY --from=builder /work/build-request-processor/target/quarkus-app/app/ /deployments/app/
COPY --from=builder /work/build-request-processor/target/quarkus-app/quarkus/ /deployments/quarkus/

EXPOSE 8080
USER 185

ENV AB_JOLOKIA_OFF=""
ENV JAVA_OPTS="-Djava.util.logging.manager=org.jboss.logmanager.LogManager"
ENV JAVA_APP_JAR="/deployments/quarkus-run.jar"
